version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - front_node_modules:/app/node_modules
    command: yarn dev
    ports:
      - "3000:3000"
    stdin_open: true
volumes:
  front_node_modules: